name: category-v
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  # NetCDF-4 libraries
  - netcdf4
  - h5netcdf
  - h5py
  - xarray
  # Data processing
  - pandas
  - numpy
  # Visualization
  - matplotlib
  - cycler
  - plotly
  # Geographic and astronomical libraries
  - pyproj
  - astropy
  # Libraries for interpolation
  - geographiclib
  # GCP libraries
  - pip:
    - google-cloud-storage
    - google-cloud-core
    - hurdat2parser
    - fsspec
    - gcsfs
    - requests
    - aiohttp
    - global-land-mask
    - cartopy
    - tropycal
    - setuptools
    - streamlit