name: category-v
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  # NetCDF-4 libraries
  - netcdf4
  - h5netcdf
  - h5py
  - xarray
  - pandas
  # GCP libraries
  - pip:
    - google-cloud-storage
    - google-cloud-core
    - hurdat2parser